### PR TITLE
Fix csproj build errors

### PR DESCRIPTION
**Pull request by wieslawsoltes**

### CODE REVIEW

**Comment by cuikp** [comment]
Can you tell me what specific error you get trying to build?

**Comment by wieslawsoltes** [comment]
> Can you tell me what specific error you get trying to build?
```

0>.NETCoreApp,Version=v8.0.AssemblyAttributes.cs(4,12): Error CS0579 : Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(13,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(14,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(16,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(17,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(18,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(19,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
0>AvRichTextBox.AssemblyInfo.cs(20,12): Error CS0579 : Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute

```

**Comment by cuikp** [comment]
Merge has been committed - Hope that fixes it -

**Comment by wieslawsoltes** [comment]
> Merge has been committed - Hope that fixes it -

Thanks, yes it fixes the issue.

**Pull request merged**
